KOREAN_NAMES = {
    "Abra": "케이시", "Aerodactyl": "프테라", "Alakazam": "후딘",
    "Arbok": "아보크", "Arcanine": "윈디", "Articuno": "프리져",
    "Beedrill": "독침붕", "Bellsprout": "모다피", "Blastoise": "거북왕",
    "Bulbasaur": "이상해씨", "Butterfree": "버터플", "Caterpie": "캐터피",
    "Chansey": "럭키", "Charmander": "파이리", "Charmeleon": "리자드",
    "Charizard": "리자몽", "Clefable": "픽시", "Clefairy": "삐삐",
    "Cloyster": "클로이스터", "Cubone": "탕구리", "Dewgong": "쥬레곤",
    "Diglett": "디그다", "Ditto": "메타몽", "Dodrio": "두트리오",
    "Doduo": "두두", "Dragonair": "신뇽", "Dragonite": "망나뇽",
    "Dratini": "미뇽", "Drowzee": "슬리프", "Dugtrio": "닥트리오",
    "Eevee": "이브이", "Ekans": "아보", "Electabuzz": "에레브",
    "Electrode": "붐볼", "Exeggcute": "아라리", "Exeggutor": "나시",
    "Farfetchd": "파오리", "Fearow": "파오리", "Flareon": "부스터",
    "Gastly": "고오스", "Geodude": "꼬마돌", "Gloom": "냄새꼴",
    "Golbat": "골뱃", "Goldeen": "콘치", "Golduck": "골덕",
    "Golem": "딱구리", "Graveler": "데구리", "Grimer": "질퍽이",
    "Growlithe": "가디", "Gyarados": "갸라도스", "Haunter": "고우스트",
    "Hitmonchan": "홍수몬", "Hitmonlee": "시라소몬", "Horsea": "쏙독",
    "Hypno": "슬리퍼", "Ivysaur": "이상해풀", "Jigglypuff": "푸린",
    "Jolteon": "썬더", "Jynx": "루주라", "Kabuto": "투구",
    "Kabutops": "투구푸스", "Kadabra": "윤겔라", "Kangaskhan": "캥카",
    "Kingler": "킹크랩", "Koffing": "독가스", "Krabby": "크랩",
    "Lapras": "라프라스", "Lickitung": "내루미", "Machamp": "괴력몬",
    "Machoke": "근육몬", "Machop": "알통몬", "Magikarp": "잉어킹",
    "Magmar": "마그마", "Magnemite": "코일", "Magneton": "레어코일",
    "Marowak": "텅구리", "Meowth": "나옹", "Metapod": "단데기",
    "Mew": "뮤", "Mewtwo": "뮤츠", "Moltres": "파이어",
    "MrMime": "마임맨", "Muk": "질뻐기", "Nidoking": "니드킹",
    "Nidoqueen": "니드퀸", "NidoranF": "니드런♀", "NidoranM": "니드런♂",
    "Nidorina": "니드리나", "Nidorino": "니드리노", "Ninetales": "나인테일",
    "Oddish": "뚜벅초", "Onix": "롱스톤", "Paras": "파라스",
    "Parasect": "파라섹트", "Persian": "페르시온", "Pidgeot": "피죤투",
    "Pidgeotto": "피죤", "Pidgey": "구구", "Pinsir": "쁘사이저",
    "Poliwag": "발챙이", "Poliwhirl": "슈륙챙이", "Poliwrath": "강챙이",
    "Ponyta": "포니타", "Porygon": "폴리곤", "Primeape": "성원숭",
    "Psyduck": "고라파덕", "Raichu": "라이츄", "Rapidash": "날쌩마",
    "Raticate": "레트라", "Rattata": "꼬렛", "Rhydon": "강철톤",
    "Rhyhorn": "뿔카노", "Sandshrew": "모래두지", "Sandslash": "고지",
    "Scyther": "스라크", "Seadra": "시드라", "Seaking": "왕콘치",
    "Seel": "쥬쥬", "Shellder": "셀러", "Slowbro": "야도란",
    "Slowpoke": "야돈", "Snorlax": "잠만보", "Spearow": "깨비참",
    "Starmie": "아쿠스타", "Staryu": "별가사리", "Tangela": "덩쿠리",
    "Tauros": "켄타로스", "Tentacool": "왕눈해", "Tentacruel": "독파리",
    "Vaporeon": "샤미드", "Venomoth": "도나리", "Venonat": "콘팡",
    "Venusaur": "이상해꽃", "Victreebel": "우츠보트", "Vileplume": "라플레시아",
    "Voltorb": "찌리리공", "Vulpix": "식스테일", "Wartortle": "어니부기",
    "Weedle": "뿔충이", "Weezing": "또가스", "Wigglytuff": "푸크린",
    "Zapdos": "썬더", "Zubat": "주뱃",
    # Gen 2+
    "Pichu": "피츄", "Marill": "마릴", "Togepi": "토게피",
    "Ampharos": "전룡", "Umbreon": "블래키", "Espeon": "에브이",
    "Typhlosion": "블레이범", "Feraligatr": "엘리게이트", "Meganium": "메가니움",
    "Lugia": "루기아", "HoOh": "칠색조", "Celebi": "세레비",
    "Pachirisu": "파치리수", "Emolga": "에몰가",
}

POKEMON_TYPES = {
    "Abra": ["Psychic"], "Aerodactyl": ["Rock", "Flying"],
    "Alakazam": ["Psychic"], "Arbok": ["Poison"], "Arcanine": ["Fire"],
    "Articuno": ["Ice", "Flying"], "Beedrill": ["Bug", "Poison"],
    "Bellsprout": ["Grass", "Poison"], "Blastoise": ["Water"],
    "Bulbasaur": ["Grass", "Poison"], "Butterfree": ["Bug", "Flying"],
    "Caterpie": ["Bug"], "Chansey": ["Normal"], "Charmander": ["Fire"],
    "Charmeleon": ["Fire"], "Charizard": ["Fire", "Flying"],
    "Clefable": ["Fairy"], "Clefairy": ["Fairy"], "Cloyster": ["Water", "Ice"],
    "Cubone": ["Ground"], "Dewgong": ["Water", "Ice"], "Diglett": ["Ground"],
    "Ditto": ["Normal"], "Dodrio": ["Normal", "Flying"], "Doduo": ["Normal", "Flying"],
    "Dragonair": ["Dragon"], "Dragonite": ["Dragon", "Flying"], "Dratini": ["Dragon"],
    "Drowzee": ["Psychic"], "Dugtrio": ["Ground"], "Eevee": ["Normal"],
    "Ekans": ["Poison"], "Electabuzz": ["Electric"], "Electrode": ["Electric"],
    "Exeggcute": ["Grass", "Psychic"], "Exeggutor": ["Grass", "Psychic"],
    "Farfetchd": ["Normal", "Flying"], "Fearow": ["Normal", "Flying"],
    "Flareon": ["Fire"], "Gastly": ["Ghost", "Poison"], "Geodude": ["Rock", "Ground"],
    "Gloom": ["Grass", "Poison"], "Golbat": ["Poison", "Flying"],
    "Goldeen": ["Water"], "Golduck": ["Water"], "Golem": ["Rock", "Ground"],
    "Graveler": ["Rock", "Ground"], "Grimer": ["Poison"], "Growlithe": ["Fire"],
    "Gyarados": ["Water", "Flying"], "Haunter": ["Ghost", "Poison"],
    "Hitmonchan": ["Fighting"], "Hitmonlee": ["Fighting"], "Horsea": ["Water"],
    "Hypno": ["Psychic"], "Ivysaur": ["Grass", "Poison"], "Jigglypuff": ["Normal", "Fairy"],
    "Jolteon": ["Electric"], "Jynx": ["Ice", "Psychic"], "Kabuto": ["Rock", "Water"],
    "Kabutops": ["Rock", "Water"], "Kadabra": ["Psychic"], "Kangaskhan": ["Normal"],
    "Kingler": ["Water"], "Koffing": ["Poison"], "Krabby": ["Water"],
    "Lapras": ["Water", "Ice"], "Lickitung": ["Normal"], "Machamp": ["Fighting"],
    "Machoke": ["Fighting"], "Machop": ["Fighting"], "Magikarp": ["Water"],
    "Magmar": ["Fire"], "Magnemite": ["Electric", "Steel"], "Magneton": ["Electric", "Steel"],
    "Marowak": ["Ground"], "Meowth": ["Normal"], "Metapod": ["Bug"],
    "Mew": ["Psychic"], "Mewtwo": ["Psychic"], "Moltres": ["Fire", "Flying"],
    "MrMime": ["Psychic", "Fairy"], "Muk": ["Poison"], "Nidoking": ["Poison", "Ground"],
    "Nidoqueen": ["Poison", "Ground"], "NidoranF": ["Poison"], "NidoranM": ["Poison"],
    "Nidorina": ["Poison"], "Nidorino": ["Poison"], "Ninetales": ["Fire"],
    "Oddish": ["Grass", "Poison"], "Onix": ["Rock", "Ground"], "Paras": ["Bug", "Grass"],
    "Parasect": ["Bug", "Grass"], "Persian": ["Normal"], "Pidgeot": ["Normal", "Flying"],
    "Pidgeotto": ["Normal", "Flying"], "Pidgey": ["Normal", "Flying"],
    "Pinsir": ["Bug"], "Poliwag": ["Water"], "Poliwhirl": ["Water"],
    "Poliwrath": ["Water", "Fighting"], "Ponyta": ["Fire"], "Porygon": ["Normal"],
    "Primeape": ["Fighting"], "Psyduck": ["Water"], "Raichu": ["Electric"],
    "Rapidash": ["Fire"], "Raticate": ["Normal"], "Rattata": ["Normal"],
    "Rhydon": ["Ground", "Rock"], "Rhyhorn": ["Ground", "Rock"],
    "Sandshrew": ["Ground"], "Sandslash": ["Ground"], "Scyther": ["Bug", "Flying"],
    "Seadra": ["Water"], "Seaking": ["Water"], "Seel": ["Water"],
    "Shellder": ["Water"], "Slowbro": ["Water", "Psychic"], "Slowpoke": ["Water", "Psychic"],
    "Snorlax": ["Normal"], "Spearow": ["Normal", "Flying"], "Starmie": ["Water", "Psychic"],
    "Staryu": ["Water"], "Tangela": ["Grass"], "Tauros": ["Normal"],
    "Tentacool": ["Water", "Poison"], "Tentacruel": ["Water", "Poison"],
    "Vaporeon": ["Water"], "Venomoth": ["Bug", "Poison"], "Venonat": ["Bug", "Poison"],
    "Venusaur": ["Grass", "Poison"], "Victreebel": ["Grass", "Poison"],
    "Vileplume": ["Grass", "Poison"], "Voltorb": ["Electric"], "Vulpix": ["Fire"],
    "Wartortle": ["Water"], "Weedle": ["Bug", "Poison"], "Weezing": ["Poison"],
    "Wigglytuff": ["Normal", "Fairy"], "Zapdos": ["Electric", "Flying"], "Zubat": ["Poison", "Flying"],
    "Pichu": ["Electric"], "Pachirisu": ["Electric"], "Emolga": ["Electric", "Flying"],
}

TYPE_COLORS = {
    "Normal":   "#A8A878", "Fire":     "#F08030", "Water":    "#6890F0",
    "Electric": "#F8D030", "Grass":    "#78C850", "Ice":      "#98D8D8",
    "Fighting": "#C03028", "Poison":   "#A040A0", "Ground":   "#E0C068",
    "Flying":   "#A890F0", "Psychic":  "#F85888", "Bug":      "#A8B820",
    "Rock":     "#B8A038", "Ghost":    "#705898", "Dragon":   "#7038F8",
    "Dark":     "#705848", "Steel":    "#B8B8D0", "Fairy":    "#EE99AC",
}

def get_korean(name: str) -> str:
    return KOREAN_NAMES.get(name, name)

def get_types(name: str) -> list:
    return POKEMON_TYPES.get(name, [])

def get_type_color(type_name: str) -> str:
    return TYPE_COLORS.get(type_name, "#A8A878")
